CREATE TABLE "car" ("car_id" INTEGER PRIMARY KEY  AUTOINCREMENT , "name" VARCHAR NOT NULL , "comment" TEXT);
CREATE TABLE "reservation" ("reservation_id" INTEGER PRIMARY KEY  AUTOINCREMENT , "who" VARCHAR NOT NULL , "date_created" DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP, "start" DATETIME NOT NULL , "end" DATETIME NOT NULL , "comment" TEXT);
